### ISSUE TITLE
Van de Graaff whiteboard blocks VR player

### ISSUE THREAD

**Issue by codecreativity** [GameLabGraz/Maroon#119]
If the VR player spawns/moves behind the whiteboard it is impossible to get back to the exit of the room

**Comment by sandra-bre** [comment]
fyi: I created a c# script and corresponding prefab called VRTK_StartPosition that automatically teleports the user to the specified position once he entered the room. therefore spawning behind the whiteboard is impossible.

**Comment by michaelholly** [comment]
Depends on #200
