### ISSUE TITLE
Teleport and navigation enhancements

### ISSUE THREAD

**Issue by michaelholly** [GameLabGraz/Maroon#140]
- [ ] Use Nav Meshes for Teleportation areas
- [ ] Fix this issue by using nav meshes (And check for invisible colliders): In Laboratory Players can teleport into objects. For example, players can teleport into the tank and can get confused and/or stuck.
- [ ]  Check if this bug is still valid and fix it: Teleportation trajectory/arc is limited in height (collides with some sort of invisible ceiling). This does not happen consistently. Limits the distance the player can teleport in one step.

**Comment by sandra-bre** [comment]
maybe see https://github.com/Unity-Technologies/NavMeshComponents for dynamic nav meshes, because our laboratory is created dynamically.
