### ISSUE TITLE
Remaining folder cleanup

### ISSUE THREAD

**Issue by codecreativity** [GameLabGraz/Maroon#195]
- [ ] Assesment system
- [ ]  Resources
- [x]  Standard Assets
- [ ] Editor
- [x] Rename 0-Refactored folder
- [x] Rename Van-de-Graaff scene files to balloon and generator

**Comment by codecreativity** [comment]
Blocked by Assesment system

**Comment by codecreativity** [comment]
Unblocked

**Comment by FlorianGlawogger** [comment]
I am not sure what the issue was originally about, but the Assessment system is not part of Maroon anymore; And there is an Editor, Resources folder, etc; so I think this can be closed
