### ISSUE TITLE
[VR?] Remove VRTK Dependencies

### ISSUE THREAD

**Issue by michaelholly** [GameLabGraz/Maroon#200]
As it seems that the development of VRTK is not progressing, the VRTK dependencies should be removed to enable further VR development.

- [x] Remove VRTK plugin
- [x] Update SteamVR plugin to the latest version
- [x] Replace all VRTK functionalities with SteamVR features.

Start with prefabs/samples of:
- [x] Button
- [x] Slider
- [x] Switch
- [x] Teleporter
- [x] Spawn Position (when entering new scene)

**Comment by sandra-bre** [comment]
I'll start with the steamVR plugins and updating :)

**Comment by danishsshaikh** [comment]
what about the new version of VRTK? It seems like v4 is the active one.

**Comment by codecreativity** [comment]
@danishsshaikh, the new version based on SteamVR is now merged. We were not sure how active VRTK will be in the future. Unfortunately we are not so sure about SteamVR either, but it's a good option for now.
