### ISSUE TITLE
Pause Menu Enhancements

### ISSUE THREAD

**Issue by sandra-bre** [GameLabGraz/Maroon#215]
- [x] The pause menu is only displayed in english, no matter what the actual displaying language is.
![image](https://user-images.githubusercontent.com/9962095/89768808-689db080-dafc-11ea-938f-6ddf568764a0.png)

- [x] When changing the language (see image above) it would be really nice when the window on the right would be closed once I changed the language or if I would have a back button that closes that window. Additionally the currently used language could be grayed out/disabled. :)

**Comment by codecreativity** [comment]
Active language is highlighted in pending PR #213 
Language change should work, maybe some issue with language manager (Check again after #213 is merged)

Related to #209
