### ISSUE TITLE
All scene loads via Maroon.SceneManager

### ISSUE THREAD

**Issue by codecreativity** [GameLabGraz/Maroon#289]
Pipe all scene changes through Maroon.SceneManager. Do not change scene via Network Manager, let Scene Manager detect if Network is enabled, then let SceneManager call NetworkManager functions on scene load for preparations.

**Comment by FlorianGlawogger** [comment]
Since we don't have the NetworkManager anymore, and as far as I am aware all scene loads already use the Maroon SceneManager, thus issue can be closed
