### ISSUE TITLE
Adjust pause menu and main menu for VR

### ISSUE THREAD

**Issue by michaelholly** [GameLabGraz/Maroon#33]
- [ ] Remove old pause menu scene from project
- [ ] Maybe re-add sound effects to menus
- [ ] Use input map instead of polling with Update()
- [ ] Make menu columns displayable and intractable in VR

In VR, the user should be able to access the menu via the menu button on the controller and change settings with the controller (e.g. with a pointer). Maybe have a main menu room in VR as well.

(Edited by Sebastian)

**Comment by codecreativity** [comment]
Also, add a Maroon logo and adjust colors to according to the logo

**Comment by sandra-bre** [comment]
depends on #185

**Comment by sandra-bre** [comment]
[CoulombsLaw] pause menu doesn't delete charges/objects any more

**Comment by codecreativity** [comment]
Depends on #200
