### ISSUE TITLE
Genetic Drift Experiment

### ISSUE THREAD

**Issue by ConnorSutton07** [GameLabGraz/Maroon#353]
A new experiment for simulating genetic drift

There will be a map consisting of the major biomes on a table, and the user will be able to parameterize the simulation by choosing the site of the initial population as well as the conditional probabilities of extinction given the climate/elevation.
As the population spreads, divides, and adapts to separate niches, their color will change to represent the growing genetic distance.

**Comment by FlorianGlawogger** [comment]
Closed as no longer being pursued
