### ISSUE TITLE
[Coulombs Law] Integrate Assessment Interface

### ISSUE THREAD

**Issue by michaelholly** [GameLabGraz/Maroon#63]
**Links and Specifications:**
[Google Doc Specifications](https://docs.google.com/document/d/1OuvOHQPKP5u_WCmugGQCrR6TpLzeY-hipCtswlNVwOc/edit?usp=sharing)

**Variables in Maroon:**
_Basic:_
- [x] Display Mode
- [x] Perspective
- [x] Experiment Rotation in 3d Mode
- [x] Simulation Running?

_Charge:_
- [x] Position
- [x] IsFixedPosition
- [x] Charge

_Ruler:_
- [x] Start Position
- [x] End Position
- [x] Distance

_Voltmeter:_
- [x] Positive Position
- [x] Negative Position
- [x] Voltage

_Visualization:_
- [x] Voltage Vis
- [x] Equipotential Line Vis
- [x] Iron Filing Vis
- [x] Vector Field Arrow Count
- [x] Position (3d only)
- [x] Rotation (3d only)

**Others:**
- [x] Test Files
- [x] Bigger UI Elements and font sizes for the slides
- [x] Works with WebGL

**Comment by michaelholly** [comment]
[Specification_Assessment_ChargeExperiment.pdf](https://github.com/GamesResearchTUG/Maroon/files/3956238/Specification_Assessment_ChargeExperiment.pdf)

**Comment by michaelholly** [comment]
blocked, depends on #64 and #65

**Comment by sandra-bre** [comment]
blocked, depends on #181
