### ISSUE TITLE
CoulombsLaw - Beauty Hacks

### ISSUE THREAD

**Issue by sandra-bre** [GameLabGraz/Maroon#97]
- [x]  When switching between perspectives (3d) the visualization plane's rotation is reset -> smoothly rotate to the wished rotation + position
- [x] 3d Version - Visualization Plane: adapt moving arrow directions when the plane is rotated (not always just move on x,y,z axis)

**Comment by michaelholly** [comment]
What is the current state of this issue?
Can we close it?
